Features/cap04
cotnesita/HTML5 pull request #15
Opened 2024-10-30 21:53 UTC by cotnesita

Capítulo 04, llamado "Llamémoslo superficie de dibujo"

2024-10-30 23:44 UTC, semanticmx commented
Escoge uno varios si quieres de estos y los agregas a la carpeta src/

https://webdesign.tutsplus.com/21-ridiculously-impressive-html5-canvas-experiments--net-14210a

Puedes hacer un archivo HTML por cada uno y agregas su screenshot correspondiente.

2024-10-30 23:44 UTC, semanticmx requested changes
unos ajustes y agregar más ejemplos

2024-10-30 23:44 UTC, semanticmx commented on cap-04/src/Index.html
> +                function fuentes(){
tómale screenshot a el resultado de esto para que lo agregues a el folder cap-04/ con el nombre screenshot.jpg

2024-11-06 14:46 UTC, semanticmx approved these changes
excelente!

2024-11-06 17:04 UTC, cotnesita commented
Listo para merge!

2024-11-06 17:04 UTC, merged