Features/cap03
cotnesita/HTML5 pull request #7
Opened 2024-10-23 18:08 UTC by cotnesita

Creación del resumen del capítulo 3, "¿Qué significa todo esto?"

2024-10-23 22:59 UTC, semanticmx requested changes

2024-10-23 22:59 UTC, semanticmx commented on cap-03/README.md
> +`<header>` <br>
cuando solo vayas a escribir una sola línea de código se pueden usar los backticks (**`**)

Pero cuando se hace un bloque de código en lugar de agregar backticks por línea puedes agrupar todo el código en tres backticks (**```**)

Entonces ajustar por favor estos bloques para que solo agregues 3 backticks al inicio y 3 al final del bloque de código.

2024-10-29 00:12 UTC, cotnesita commented
@semanticmx Listo! Ya corregí todo el código.

2024-10-29 14:44 UTC, semanticmx approved these changes
muy bien!

2024-10-29 16:14 UTC, merged